-   id: terraform-linter
    name: Terraform linter
    description: Terraform linting via docker_image
    entry: cybergrx/terraform-linter:latest
    language: docker_image
    files: \.(tf|tfvars)$